// [category, difficulty, question, code, [options], correctIndex, explanation]
const CATEGORIES=["C Fundamentals","Variables and Data Types","Operators and Expressions","If-Else and Switch","Loops","Arrays and Strings","Functions","Pointers","Structures","Output Prediction and Debugging"];
const POINTS={Easy:10,Medium:20,Hard:30};
const RAW=[
[0,"Easy","Which header file declares printf()?","",["<stdlib.h>","<stdio.h>","<string.h>","<math.h>"],1,"printf is declared in <stdio.h>, the standard input/output header."],
[0,"Easy","Where does execution of a C program begin?","",["The first function in the file","The function main()","The function start()","The first #include line"],1,"Every hosted C program starts running at main()."],
[0,"Easy","What does this command do?","gcc hello.c -o hello",["Deletes hello.c","Runs hello.c as a script","Compiles hello.c into an executable named hello","Compiles hello.c into a library"],2,"The -o option sets the name of the output file."],
[0,"Medium","Which symbol ends most statements in C?","",["Colon :","Period .","Semicolon ;","Comma ,"],2,"A semicolon terminates a statement in C."],
[1,"Easy","On most modern systems, how many bytes does an int use?","",["1","2","4","16"],2,"int is typically 4 bytes (32 bits), although the C standard only sets a minimum."],
[1,"Easy","Which is a valid C variable name?","",["2total","my-var","_count","int"],2,"Names may start with a letter or underscore. Digits first, hyphens, and keywords are not allowed."],
[1,"Easy","Which format specifier prints a double with printf?","",["%d","%c","%f","%s"],2,"%f prints floating-point values such as double."],
[1,"Medium","What is printed?","int x = 7 / 2;\nprintf(\"%d\", x);",["3.5","3","4","2"],1,"Both operands are int, so integer division discards the fraction: 7 / 2 is 3."],
[2,"Easy","What is the value of 10 % 3?","",["3","0","1","3.33"],2,"The % operator gives the remainder. 10 divided by 3 leaves 1."],
[2,"Medium","What is printed?","int a = 5;\nint b = a++;\nprintf(\"%d %d\", a, b);",["5 5","6 5","6 6","5 6"],1,"a++ returns the old value (5) to b, then a becomes 6."],
[2,"Easy","Which operator tests whether two values are equal?","",["=","==","!=","=>"],1,"== compares values. A single = assigns."],
[2,"Medium","What does this expression evaluate to?","5 > 3 && 2 > 4",["1","0","5","2"],1,"5 > 3 is true but 2 > 4 is false, so && gives 0."],
[3,"Medium","What happens if a case in a switch has no break?","",["A compile error","Execution falls through into the next case","The program exits","The default case runs"],1,"Without break, execution continues into the following case labels (fall-through)."],
[3,"Easy","What is printed?","int x = 10;\nif (x > 5) printf(\"A\");\nelse printf(\"B\");",["A","B","AB","Nothing"],0,"x > 5 is true, so only the if branch runs."],
[3,"Easy","What is printed?","int x = 0;\nif (x) printf(\"T\");\nelse printf(\"F\");",["T","F","TF","Compile error"],1,"In C, 0 is false. The condition fails, so the else branch prints F."],
[3,"Hard","What is printed?","switch (2) {\n  case 1: printf(\"1\");\n  case 2: printf(\"2\");\n  case 3: printf(\"3\"); break;\n  default: printf(\"D\");\n}",["2","23","123","23D"],1,"It jumps to case 2, prints 2, falls through to case 3, prints 3, then breaks."],
[4,"Easy","What is printed?","for (int i = 0; i < 3; i++)\n  printf(\"%d\", i);",["123","012","0123","210"],1,"i takes the values 0, 1, 2 and stops when i reaches 3."],
[4,"Medium","Which loop always runs its body at least once?","",["for","while","do-while","None of them"],2,"do-while tests its condition after the body."],
[4,"Easy","What is printed?","int i = 1;\nwhile (i <= 3) {\n  printf(\"%d \", i);\n  i++;\n}",["1 2 3 ","0 1 2 ","1 2 ","1 2 3 4 "],0,"The loop prints 1, 2 and 3, then i becomes 4 and the loop ends."],
[4,"Hard","What is printed?","for (int i = 0; i < 5; i++) {\n  if (i == 2) continue;\n  if (i == 4) break;\n  printf(\"%d\", i);\n}",["0123","013","01","0134"],1,"i=2 is skipped by continue and i=4 stops the loop, leaving 0, 1 and 3."],
[5,"Easy","Which indexes are valid for int a[5]?","",["1 to 5","0 to 5","0 to 4","0 to 6"],2,"Arrays are zero-based, so a 5-element array has indexes 0 to 4."],
[5,"Medium","What does strlen(\"Hello\") return?","",["4","5","6","0"],1,"strlen counts the characters before the terminating '\\0', so it returns 5."],
[5,"Medium","How many bytes does this array occupy?","char s[] = \"Hi\";",["2","3","4","1"],1,"The string has 2 characters plus the terminating null character, so 3 bytes."],
[5,"Easy","What is printed?","int a[] = {1, 2, 3};\nprintf(\"%d\", a[1] + a[2]);",["3","4","5","6"],2,"a[1] is 2 and a[2] is 3, so the sum is 5."],
[6,"Easy","Which return type means a function returns no value?","",["null","void","empty","int"],1,"void declares that a function returns nothing."],
[6,"Medium","What is printed?","void f(int x) { x = 10; }\nint main() {\n  int n = 5;\n  f(n);\n  printf(\"%d\", n);\n}",["5","10","0","Compile error"],0,"C passes arguments by value, so f changes only its own copy."],
[6,"Medium","What is a function prototype for?","",["To run the function earlier","To declare the function's name and types before it is used","To make the function faster","To delete the function"],1,"A prototype tells the compiler the return type and parameters before the definition."],
[6,"Medium","What is printed?","int sq(int n) { return n * n; }\nprintf(\"%d\", sq(3) + sq(2));",["10","13","25","12"],1,"sq(3) is 9 and sq(2) is 4, so the total is 13."],
[7,"Easy","What does the & operator give when placed before a variable?","",["Its value","Its address","Its size","Its type"],1,"&x is the memory address of x."],
[7,"Medium","What is printed?","int x = 5;\nint *p = &x;\n*p = 9;\nprintf(\"%d\", x);",["5","9","The address of x","Undefined"],1,"p points to x, so assigning through *p changes x to 9."],
[7,"Hard","What happens when you dereference a NULL pointer?","",["It returns 0","It returns -1","Undefined behavior, usually a crash","It allocates memory"],2,"Dereferencing NULL is undefined behavior and normally crashes the program."],
[7,"Hard","What is printed?","int a[] = {10, 20, 30};\nint *p = a;\nprintf(\"%d\", *(p + 2));",["10","20","30","Address"],2,"p + 2 points to the third element, so *(p + 2) is 30."],
[8,"Easy","Which keyword defines a structure type?","",["class","struct","record","object"],1,"C uses the struct keyword."],
[8,"Medium","If p is a pointer to a struct with member age, how do you read age?","",["p.age","p->age","p::age","&p.age"],1,"The arrow operator accesses a member through a pointer; it is shorthand for (*p).age."],
[8,"Easy","What is printed?","struct P { int x; int y; };\nstruct P a = {1, 2};\nprintf(\"%d\", a.x + a.y);",["12","3","1","2"],1,"a.x is 1 and a.y is 2, so the sum is 3."],
[8,"Easy","Can one struct hold members of different types?","",["No, all must match","Yes","Only two types","Only numbers"],1,"Structures group members of different types, such as an int and a char array."],
[9,"Medium","This code prints \"Yes\" even though the intent was to compare. What is the bug?","int x = 5;\nif (x = 10) printf(\"Yes\");",["Missing semicolon","= assigns 10 to x instead of comparing with ==","x must be float","printf is misspelled"],1,"x = 10 assigns and evaluates to 10, which is true. The comparison should be x == 10."],
[9,"Medium","What is wrong with this loop?","int arr[3] = {1, 2, 3};\nfor (int i = 0; i <= 3; i++)\n  printf(\"%d\", arr[i]);",["Nothing is wrong","It reads arr[3], which is out of bounds","arr must be global","i must be float"],1,"Valid indexes are 0 to 2. Using <= reads arr[3], which is undefined behavior."],
[9,"Hard","What is printed?","printf(\"%.1f\", 5 / 2.0);",["2","2.0","2.5","3"],2,"2.0 is a double, so the division is 2.5, printed with one decimal."],
[9,"Hard","What is the problem here?","int x;\nprintf(\"%d\", x);",["x is a keyword","x is uninitialized, so its value is indeterminate","%d is the wrong specifier","Nothing, it prints 0"],1,"A local variable that is never assigned holds an unpredictable value."]
];
const QUESTIONS=RAW.map((r,i)=>({id:i,cat:r[0],diff:r[1],pts:POINTS[r[1]],q:r[2],code:r[3],opts:r[4],ans:r[5],exp:r[6]}));
